name: "Pre Merge Checks"

on:
  # Allows to run this workflow when a commit it pushed to the branch
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - master
      - develop
  # Allows to run this workflow when a Pull Request is made with the set target branch
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - master
      - develop
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle # Will automatically perform wrapper validation on each execution.
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}

      - name: Run lint checks and unit tests
        run: ./gradlew lintRelease testDebugUnitTest --parallel --build-cache
